#in day 5 we are learn about comment , escapsequence , print() in python
# --->this is a singale line comment

" " " this an mlutyline comment " " " #---->this a multyline comment

' ' ' lorem(34) ' ' ' #--->this the another way to write multyline comments.........


#---->this the print function....
print("My Aim is to become an army officer")


#Escapsequense are.....
#\n-->for new line....
#\"-->for duble quate....
#\'-->for single quote.....

