#create a program to capable of displaying question to the user like KBC(koun banega cororpati)....

#use list data type to store the question and answer......

#displaying the final amount the person is taking home after playing the game.