# in day 13 we are learn about string method.......
a="tarinee!! !!!!!! !!!!!!"
print(len(a))#len function give length of the string....

print(a.upper())#upper function changes every charecter of string to uppercase

print(a.lower())#lower function changes every charecter of string to lowercase......

print(a.rstrip("!"))#rstrip function remove all trelliing charecter....

print(a.replace("tarinee" , "harry"))#replace function replace the charecter with given charecter............

print(a.split(" "))#split function convert the string to list to the besis of " ".......

blog_Heading="introduction to python"
print(blog_Heading.capitalize())#this function convert first charecter of the string to capital letter.....


print(blog_Heading.center(70))#this function put the string to the center of the consol.....



print(a.count("!"))#this function return the number of occurance of the charecter in the string....


print(a.endswith("!"))#this function return true if the string ends with the given charecter....


print(a.find("a"))#this function return the index number of the given charecter......

print(a.index("a"))#in this function if the charecter is not present in the string then the function raise error...........


print(blog_Heading.isalnum())#this function return true if the the string contains only 'A'-'Z' and 'a'-'z' and 0-9 charecter....


print(blog_Heading.isalpha())


print(a.isprintable())#this function return true if the charecter present in the string is printable........

str="    "
print(str.isspace())#this function return true if the string only have white spaces .......


print(blog_Heading.istitle())#this function return true if the strig is a title......


print(a.startswith("tarinee"))#this function return true if the string start with given string.......

print(blog_Heading.title())#this function convert string to title....







