#in day 87 we are learn  about shutil module...in python...
#shutil module provids a higher level interface for working with file and directories.
import shutil
shutil.copy("src" , "dst")#this function copy the file src to dst....

shutil.copy2("src" , "dst")#this function is very similar to the copy function but also copy the metadata.....

shutil.copytree("src"  ,"dst")#thsi function is used to copy the folder......


shutil.move("src" , "dst")#this functio moves the file src to dst.....

shutil.rmtree()#this function delete the directori tree.....

#if you want to delet the file then you can uses os.remove method......